%% Compile the wrapper for readOBJ
clc
mex readOBJ_mex.cpp ...    
    -I../libigl/include ...
    -I../Eigen   

% Load an OBJ mesh
%[V,F,VN,FN] = readOBJ_mex('../shared/bumpy-cube.obj');

% Plot the mesh
%trimesh(F,V(:,1),V(:,2),V(:,3));
%axis vis3d;

%%
clc
mex writeOBJ_mex.cpp ...
    -I../libigl/include ...
    -I../Eigen 
%%
clc
mex writeOFF_mex.cpp ...
    -I../libigl/include ...
    -I../Eigen 
%%
clc
mex readOFF_mex.cpp ...
    -I../libigl/include ...
    -I../Eigen 
    

%%
%clc;
%mex compLaplacian_mex.cpp ...
%    -I../../include ...    
%    -I../../../Eigen     
%    %-I/opt/local/include/eigen3 %% Change this path to point to your copy of Eigen

%% compile triangle wrapper
clc
mex -g triangulate_mex.cpp ...    
    ../libigl/external/triangle/triangle.c ...       
    -DNO_TIMER ...  
    -DTRILIBRARY ... 
    -I../libigl/external/triangle ...
    -I../libigl/include ...    
    -I../Eigen      

   %-DIGL_STATIC_LIBRARY ...
    %../libigl/include/igl/triangle/triangulate.cpp ...
    %../libigl/external/triangle/triangle.c   
    %../libigl/include/igl/matlab/prepare_lhs.cpp ...
    %../libigl/include/igl/matlab/parse_rhs.cpp ...

%%
clc;
    includefilepaths = {...        
        '../libigl/include/',...
        '../Eigen/',...
        '../libigl/external/triangle/'
        };
    
    libfilepaths = {...
        ['./'],...
        ['../']};
    
    libfilenames = { };
    
    includeoptions = cellfun(@(x) {['-I',x]},includefilepaths);
    libpathoptions = cellfun(@(x) {['-L',x]},libfilepaths);
    libfileoptions = cellfun(@(x) {['-l',x]},libfilenames);

    mex(includeoptions{:},...        
        '-DNO_TIMER',...
        'triangulate_mex.cpp','../libigl/include/igl/triangle/triangulate.cpp');
    
            %'../libigl/include/igl/triangle/triangulate.cpp
    %'../libigl/external/triangle/triangle.c',...

